title = "Charlie Bury"
baseURL = "https://www.charliebury.com/"
languageCode = "en-gb"
theme = ["ananke"]
resourceDir = "themes/ananke/resources"

DefaultContentLanguage = "en"
Paginate = 12 
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Charlie Bury"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  disable_share = true
  text_color = "dark-gray"
  author = ""
  favicon = ""
  site_logo = ""
  description = "Charlie Bury | Screenwriter & Author"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  recent_posts_number = 3
  commentoEnable = false
  mainSections = []
  custom_css = ["css/custom.css"]
  date_format = "2 January 2006"
  show_reading_time = false

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/charliebury"

[[params.ananke_socials]]
  name = "letterboxd"
  url = "https://boxd.it/3wZi3"
  label = "Letterboxd"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5
  
[[menu.main]]
  name = "Screenplays"
  url = "/screenplays/"
  weight = 10

[[menu.main]]
  name = "Prose & Poetry"
  url = "/prose-poetry/"
  weight = 20

[[menu.main]]
  name = "Script Consulting"
  url = "/script-consulting/"
  weight = 40

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 50 

